"""initial schema

Revision ID: 49565e994140
Revises: 
Create Date: 2026-07-05 01:32:02.435367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '49565e994140'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('orbit', sa.String(), nullable=True),
    sa.Column('gpu_class', sa.String(), nullable=False),
    sa.Column('supported_models_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('downlink_mbps', sa.Integer(), nullable=False),
    sa.Column('power_state', sa.String(), nullable=False),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.Column('compliance_tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_minutes', sa.Float(), nullable=False),
    sa.Column('next_contact_minutes', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ground_stations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latency_minutes', sa.Float(), nullable=False),
    sa.Column('downlink_mbps', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('area_of_interest_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sensor', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('compute_preference', sa.String(), nullable=False),
    sa.Column('max_cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('selected_route_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq')
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('geojson_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_files_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('routing_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('selected_node_id', sa.String(), nullable=False),
    sa.Column('selected_ground_station_id', sa.String(), nullable=True),
    sa.Column('fallback_node_id', sa.String(), nullable=True),
    sa.Column('estimated_latency_minutes', sa.Float(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasons_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_decisions')
    op.drop_table('results')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_table('jobs')
    op.drop_table('ground_stations')
    op.drop_table('compute_nodes')
    # ### end Alembic commands ###
